name: hw-tracking

on:
  push:
    branches: [dev, tracking]
  pull_request:
    
defaults:
  run:
    working-directory: ./
jobs:
  tracking:
    runs-on: self-hosted
    timeout-minutes: 10
    env:
      shell: bash
      working-directory: ./
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./src
      run: bash -c ". ~/.bashrc;cargo build"
    - name: Link
      working-directory: ./src
      run: ln -vs /sys-runner/Cars.mp4 ./Cars.mp4
    - name: Copy
      working-directory: ./
      run: bash -c '. ~/.bashrc;rm -r "/sys-runner/${{ github.actor }}/2";mkdir -p "/sys-runner/${{ github.actor }}/2";cp -r "./"* "/sys-runner/${{ github.actor }}/2/"'
    - name: Run
      working-directory: ./src
      run: | 
           bash -c '. ~/.bashrc;/usr/bin/time -o "/sys-runner/${{ github.actor }}/2/runtime" -f "Elapsed real:%E\nNumber of page faults:%F\nCPU-seconds (kernel):%S\nCPU-seconds (user):%U\nswapped out:%W\ncontext-switched-involuntarily:%c\ncontext-switched-voluntarily:%w" cargo run -- -f Cars.mp4 >> "/sys-runner/${{ github.actor }}/2/output"'
           echo "runtime="$(cat "/sys-runner/${{ github.actor }}/2/runtime") >> $GITHUB_ENV
           echo "output="$(cat "/sys-runner/${{ github.actor }}/2/output") >> $GITHUB_ENV
           cat "/sys-runner/${{ github.actor }}/2/runtime"
           echo "----"
           cat "/sys-runner/${{ github.actor }}/2/output"
    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
                const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
                github.issues.createComment({ issue_number, owner, repo, body: "Messungen:\n${{ env.runtime }}\n\nAusgabe:\n1. ${{ env.output }}" });
